name: Build, Test and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
      VERSION: 1.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          googletest \
          debhelper \
          dh-make \
          dpkg-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DBUILD_TESTING=ON \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_CXX_STANDARD=11

    - name: Build project
      run: |
        cd build
        make -j$(nproc)
        make DESTDIR=../install install

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --verbose

    - name: Prepare DEB package structure
      run: |
        mkdir -p rk2-package/DEBIAN
        mkdir -p rk2-package/usr/bin
        cp install/usr/bin/rk2_main rk2-package/usr/bin/

        # Создаем контрольный файл
        cat > rk2-package/DEBIAN/control <<EOF
        Package: rk2
        Version: ${{ env.VERSION }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: RK2 Design Pattern Implementation
         This package contains the implementation of Proxy design pattern
         for the RK2 project. Includes tests and examples.
        EOF

        # Создаем скрипты установки/удаления (опционально)
        echo '#!/bin/sh' > rk2-package/DEBIAN/postinst
        echo 'echo "RK2 installed successfully!"' >> rk2-package/DEBIAN/postinst
        chmod 755 rk2-package/DEBIAN/postinst

    - name: Build DEB package
      run: |
        dpkg-deb --build --root-owner-group rk2-package
        mv rk2-package.deb rk2_${{ env.VERSION }}_amd64.deb
        mkdir -p artifacts
        mv rk2_${{ env.VERSION }}_amd64.deb artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          artifacts/rk2_${{ env.VERSION }}_amd64.deb
          build/rk2_main

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: RK2 v${{ env.VERSION }}
        body: |
          ### RK2 Proxy Pattern Implementation
          **Version**: ${{ env.VERSION }}
          **Build Type**: ${{ env.BUILD_TYPE }}

          Includes:
          - Proxy design pattern implementation
          - Unit tests
          - DEB package for Ubuntu

          SHA: ${{ github.sha }}
        files: |
          artifacts/rk2_${{ env.VERSION }}_amd64.deb
          build/rk2_main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
