name: Build, Test and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      VERSION: 1.0.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          googletest \
          debhelper \
          dpkg-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_STANDARD=11

    - name: Build project
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Create DEB package
      run: |
        mkdir -p rk2-package/usr/bin
        cp build/rk2_main rk2-package/usr/bin/

        mkdir -p rk2-package/DEBIAN
        cat > rk2-package/DEBIAN/control <<EOF
        Package: rk2
        Version: ${{ env.VERSION }}
        Section: utils
        Priority: optional
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: RK2 Project - Proxy Pattern Implementation
         This package contains the executable for RK2 project
         implementing Proxy design pattern.
        EOF

        dpkg-deb --build --root-owner-group rk2-package
        mv rk2-package.deb rk2_${{ env.VERSION }}_amd64.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rk2-package
        path: |
          rk2_${{ env.VERSION }}_amd64.deb
          build/rk2_main

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: RK2 v${{ env.VERSION }}
        body: |
          ### RK2 Release
          **Version**: ${{ env.VERSION }}
          **Build date**: $(date -u +'%Y-%m-%d %H:%M:%S')

          Includes:
          - Proxy pattern implementation
          - Unit tests
          - DEB package
        files: rk2_${{ env.VERSION }}_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
