name: Build, Test and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Prepare workspace
      run: |
        if [ -d "rk2" ]; then
          echo "Moving files from rk2/ to root..."
          mv rk2/* .
          mv rk2/.* . 2>/dev/null || true
          rmdir rk2
        fi
        
        echo "Final structure:"
        ls -la
        
        if [ ! -f "CMakeLists.txt" ]; then
          echo "ERROR: CMakeLists.txt not found!"
          exit 1
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          googletest \
          debhelper \
          dpkg-dev

    - name: Build and Test
      run: |
        mkdir -p build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_STANDARD=11 \
          --fresh
        
        make -j$(nproc)
        ctest --output-on-failure

    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin
        cp build/rk2_main package/usr/bin/
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: rk2
        Version: ${{ env.VERSION }}
        Architecture: amd64
        Maintainer: Your Name ilazayzev@gmail.com
        Description: RK2 Project - Proxy Pattern Implementation
        EOF
        
        dpkg-deb --build --root-owner-group package
        mv package.deb rk2_${{ env.VERSION }}_amd64.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: rk2_${{ env.VERSION }}_amd64.deb

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: RK2 v${{ env.VERSION }}
        body: |
          ### RK2 Release ${{ env.VERSION }}
          **Build date**: $(date -u +'%Y-%m-%d %H:%M:%S')
          **Commit**: ${{ github.sha }}
          
          Includes:
          - Proxy pattern implementation
          - Unit tests
          - DEB package for Ubuntu
        files: rk2_${{ env.VERSION }}_amd64.deb
