name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Добавляем явные разрешения
      packages: write
      releases: write  # Ключевое разрешение для создания релизов

    steps:
    - uses: actions/checkout@v4

    - name: Fix directory structure
      run: |
        # Проверяем структуру
        echo "Initial structure:"
        ls -la
        
        # Если файлы внутри rk2/rk2/
        if [ -d "rk2/rk2" ]; then
          echo "Moving files from rk2/rk2 to root"
          mv rk2/rk2/* .
          mv rk2/rk2/.git* . || true
          rm -rf rk2
        # Если файлы просто в rk2/  
        elif [ -d "rk2" ]; then
          echo "Moving files from rk2 to root"
          mv rk2/* .
          mv rk2/.git* . || true
          rm -rf rk2
        fi

        echo "Final structure:"
        ls -la

        # Проверка CMakeLists.txt
        if [ ! -f "CMakeLists.txt" ]; then
          echo "ERROR: CMakeLists.txt still not found!"
          echo "Current files:"
          ls -la
          exit 1
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          googletest \
          debhelper \
          dpkg-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_STANDARD=11 \
          --fresh

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --verbose

    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin
        cp build/rk2_main package/usr/bin/
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: rk2
        Version: ${{ env.VERSION }}
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: RK2 Project
        EOF
        
        dpkg-deb --build --root-owner-group package
        mv package.deb rk2_${{ env.VERSION }}_amd64.deb

    - uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: rk2_${{ env.VERSION }}_amd64.deb

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: RK2 v${{ env.VERSION }}
        body: |
          ### RK2 Release
          **Version**: ${{ env.VERSION }}
          **Build date**: $(date -u +'%Y-%m-%d %H:%M:%S')
          
          Contents:
          - Proxy pattern implementation
          - Unit tests
          - DEB package for Ubuntu
        files: rk2_${{ env.VERSION }}_amd64.deb
