name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      VERSION: 1.0.0

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'project'  # Явно указываем путь для checkout

    - name: Prepare workspace
      run: |
        # Перемещаем все файлы в корень workspace
        mv project/* .
        mv project/.git* . || true
        rmdir project

        # Проверяем наличие CMakeLists.txt
        if [ ! -f "CMakeLists.txt" ]; then
          echo "ERROR: CMakeLists.txt not found!"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          googletest \
          debhelper \
          dpkg-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=ON \
          -DCMAKE_CXX_STANDARD=11 \
          --fresh

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --verbose

    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin
        cp build/rk2_main package/usr/bin/
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<EOF
        Package: rk2
        Version: ${{ env.VERSION }}
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: RK2 Project
        EOF
        
        dpkg-deb --build --root-owner-group package
        mv package.deb rk2_${{ env.VERSION }}_amd64.deb

    - uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: rk2_${{ env.VERSION }}_amd64.deb

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ env.VERSION }}
        name: RK2 v${{ env.VERSION }}
        body: |
          Automatic build of RK2 project
          - Version: ${{ env.VERSION }}
          - SHA: ${{ github.sha }}
        files: rk2_${{ env.VERSION }}_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
