name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.0

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          googletest \
          debhelper \
          dpkg-dev

    - name: Configure and Build
      run: |
        mkdir build && cd build
        cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Create DEB package
      run: |
        mkdir -p rk2-package/usr/bin
        cp build/rk2_main rk2-package/usr/bin/
        
        mkdir -p rk2-package/DEBIAN
        cat > rk2-package/DEBIAN/control <<EOF
        Package: rk2
        Version: ${{ env.VERSION }}
        Architecture: amd64
        Maintainer: Your Name <your.email@example.com>
        Description: RK2 Project - Proxy Pattern Implementation
        Depends: libc6 (>= 2.34)
        EOF
        
        dpkg-deb --build rk2-package
        mv rk2-package.deb rk2_${{ env.VERSION }}_amd64.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: deb-package
        path: rk2_${{ env.VERSION }}_amd64.deb

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: RK2 v${{ env.VERSION }}
        body: |
          Automatic build of RK2 project
          - Includes proxy pattern implementation
          - Version: ${{ env.VERSION }}
        files: rk2_${{ env.VERSION }}_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
